pdp_django/blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView().as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView().as_view(), name='delete'),
]

pdp_django/pdp_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from pdp_django.views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, insecure=True) + static(settings.ASSETS_URL, document_root=settings.ASSETS_ROOT, insecure=True)

handler400 = 'pdp_django.views.custom_400'
handler403 = 'pdp_django.views.custom_403'
handler404 = 'pdp_django.views.custom_404'
handler500 = 'pdp_django.views.custom_500'

pdp_django/blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
#from django.core.urlresolvers import reverse #django 버젼이 1.9 이하일 경우
from django.urls import reverse #django 버젼이 1.10 이상일 경우
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='제목 영역에 쓰일 단어')
    discription = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='간단한 설명')
    content = models.TextField('CONTENT', help_text='컨텐츠 내용')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

pdp_django/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

pdp_django/blog/views.py
from django.http import request
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView

from blog.models import Post
from tagging.models import Tag, TaggedItem
from tagging.views import TaggedObjectList

from django.views.generic.edit import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from pdp_django.views import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.
class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

class PostLV(ListView):
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    #paginate_by = 2
    model = Post

    def index(request):
        post_list = Post.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 10)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return render(request, 'blog/post_all.html', { 'posts': posts })

class PostTOL(TaggedObjectList):
    model = Post
    template_name = 'tagging/tagging_post_list.html'

class PostDV(DetailView):
    model = Post

class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    month_format = '%m' # %b 형태가 한글인 문제로 월 형태를 숫자로 변경
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    month_format = '%m' # %b 형태가 한글인 문제로 월 형태를 숫자로 변경
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    month_format = '%m' # %b 형태가 한글인 문제로 월 형태를 숫자로 변경
    date_field = 'modify_date'

# Formview
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=schWord) |
                    Q(discription__icontains=schWord) | Q(content__icontains=schWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'discription', 'content', 'tag']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'discription', 'content', 'tag']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

pdp_django/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}Blog Post List{% endblock %}
{% block top_title %}Blog Post list{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-9 col-sm-7">
        <div class="row">
            {% for post in posts %}
            <div class="col-sm-12 col-md-12">
                <div class="single-blog single-column">
                    <div class="post-content overflow">
                        <h2 class="post-title bold"><a href='{{post.get_absolute_url}}'>{{ post.title }}</a></h2>
                        <h3 class="post-author"><a href="#">{{ post.owner }}</a></h3>
                        <h3 class="post-author">{{ post.modify_date|date:"N d, Y" }}</h3>
                        <p>{{ post.discription|slice:"0:100" }}</p>
                        <a href="{{post.get_absolute_url}}" class="read-more">View More</a>
                        <div class="post-bottom overflow">
                            <ul class="nav navbar-nav post-nav">
                                <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="blog-pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">이전 페이지</a></li>
                {% endif %}

                {% for i in posts.paginator.page_range %}
                    {% if post.number == i %}
                    <li class="active">{{ i }}</li>
                    {% else %}
                    <li><a href="?page={{i}}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.next_page_number }}">다음 페이지</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="col-md-3 col-sm-5">
        <div class="sidebar blog-sidebar">
            <div class="sidebar-item categories">
                <h3>Categories</h3>
                <ul class="nav navbar-stacked">
                    <li><a href="#">Lorem ipsum<span class="pull-right">(1)</span></a></li>
                    <li class="active"><a href="#">Dolor sit amet<span class="pull-right">(8)</span></a></li>
                    <li><a href="#">Adipisicing elit<span class="pull-right">(4)</span></a></li>
                    <li><a href="#">Sed do<span class="pull-right">(9)</span></a></li>
                    <li><a href="#">Eiusmod<span class="pull-right">(3)</span></a></li>
                    <li><a href="#">Mockup<span class="pull-right">(4)</span></a></li>
                    <li><a href="#">Ut enim ad minim <span class="pull-right">(2)</span></a></li>
                    <li><a href="#">Veniam, quis nostrud <span class="pull-right">(8)</span></a></li>
                </ul>
            </div>
            <div class="sidebar-item tag-cloud">
                <h3>Tag Cloud</h3>
                <ul class="nav nav-pills">
                    <li><a href="#">Corporate</a></li>
                    <li><a href="#">Joomla</a></li>
                    <li><a href="#">Abstract</a></li>
                    <li><a href="#">Creative</a></li>
                    <li><a href="#">Business</a></li>
                    <li><a href="#">Product</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pdp_django/blog/templates/blog/post_archive.html
{% extends "base.html" %}

{% block title %}Blog Post Archive {% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives Until {% now "N d, Y" %}</h1>
        <ul>
            {% for date in date_list %}
                <li style="display:inline;">
                    <a href="{% url 'blog:post_year_archive' date|date:'Y'%}">Year-{{ date|date:"Y" }}</a>
                </li>
            {% endfor %}
        </ul>
        <br />

        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}

{% block title %}Blog Post Archive {% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ day|date:"Y-m-d" }}</h1>

        <div>
            <ul>
                {% for post in object_list %}
                    <li>
                        {{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href=""{{ post.get_absolute_url }}><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}

{% block title %}Blog Post Archive {% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ month|date:"Y-m" }}</h1>

        <ul>
            {% for date in date_list %}
                <li style="display:inline;">
                    <a href="{% url 'blog:post_day_archive' date|date:'Y' date|date:'m' date|date:'d' %}">Day-{{ date|date:"d" }}</a>
                </li>
            {% endfor %}
        </ul>
        <br />

        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}

{% block title %}Blog Post Archive {% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Archives for {{ year|date:"Y" }}</h1>

        <ul>
            {% for date in date_list %}
                <li style="display:inline;">
                    <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">Month-{{ date|date:"m" }}</a>
                </li>
            {% endfor %}
        </ul>
        <br />

        <div>
            <ul>
                {% for post in object_list %}
                    <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_change_list.html
{% extends "base.html" %}

{% block title %}Blog Post Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Change - 사용자 : {{user}}</h1>

        <table class="change-list">
            <tr>
                <th>제목</th>
                <th>설명</th>
                <th>등록자</th>
                <th>수정</th>
                <th>삭제</th>
            </tr>

            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.discription }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'blog:update' item.id %}">수정</a></td>
                    <td><a href="{% url 'blog:delete' item.id %}">삭제</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}Blog Post Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Delete - 사용자 : {{user}}</h1>

        <form action="" method="post">{% csrf_token %}
            <p>정말로 해당 포스트 [ "{{ object }}" ] 를 삭제하시겠습니까 ?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}Blog Post Detail{% endblock %}
{% block top_title %}{{ object.title }}{% endblock %}
{% block top_desc %}{{ object.modify_date|date:"j F Y" }}{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-9 col-sm-7">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="single-blog blog-details two-column">
                    <div class="post-content overflow">
                        <h2 class="post-title bold"><a href="#">{{ object.title }}</a></h2>
                        <h3 class="post-author"><a href="#">{{ object.owner }}</a></h3>
                        {{ object.content|linebreaks }}
                        <div class="post-bottom overflow">
                            <ul class="nav navbar-nav post-nav" style="display:none;">
                                <li><a href="#"><i class="fa fa-tag"></i>Creative</a></li>
                                <li><a href="#"><i class="fa fa-heart"></i>32 Love</a></li>
                                <li><a href="#"><i class="fa fa-comments"></i>3 Comments</a></li>
                            </ul>
                        </div>
                        <div class="blog-share">
                            <span class='st_facebook_hcount'></span>
                            <span class='st_twitter_hcount'></span>
                            <span class='st_linkedin_hcount'></span>
                            <span class='st_pinterest_hcount'></span>
                            <span class='st_email_hcount'></span>
                        </div>
                        <div class="response-area">
                            <h2 class="bold">Comments</h2>
                            {% load disqus_tags %}
                            {% disqus_show_comments %}
                        </div><!--/Response-area-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-5">
        <div class="sidebar blog-sidebar">
            <div class="sidebar-item categories">
                <h3>Categories</h3>
                <ul class="nav navbar-stacked">
                    <li class="active"><a href="#">카테고리 수정필요<span class="pull-right">(갯수)</span></a></li>
                </ul>
            </div>
            <div class="sidebar-item tag-cloud">
                <h3><a href="{% url 'blog:tag_cloud' %}">Tag Cloud</a></h3>
                <ul class="nav nav-pills">
                    {% load tagging_tags %}
                    {% tags_for_object object as tags %}
                    {% for tag in tags %}
                    <li><a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pdp_django/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}Blog Post Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Post Create/Update - 사용자 : {{user}}</h1>

        <form action="" method="post">{% csrf_token %}
            {% if form.errors %}
                <p class="errornote">앗 이런! 입력한 내용에 문제가 있네요.</p>
            {% endif %}

            <p>본인의 포스트를 추가하거나 수정할 수 있습니다.</p>

            <fieldset class="aligned">
                <div class="form-row">{{ form.title.label_tag }} {{ form.title }}</div>
                <div class="form-row">{{ form.slug.label_tag }} {{ form.slug }}</div>
                <div class="form-row">{{ form.discription.label_tag }} {{ form.discription }}</div>
                <div class="form-row">{{ form.content.label_tag }} {{ form.content }}</div>
                <div class="form-row">{{ form.tag.label_tag }} {{ form.tag }}</div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" value="Submit" />
            </div>

            <script type="text/javascript">$('#id_title').focus();</script>
        </form>
    </div>
{% endblock %}

pdp_django/blog/templates/blog/post_search.html
{% extends 'base.html' %}

{% block title %}Blog Post Search{% endblock %}

{% block content %}
    <div id="content">
        <h1>Blog Search</h1>

        <form action="." method="post"> {% csrf_token %}
            {{ form.as_table }}
            <input type="submit" value="Submit" />
        </form>

        <br /><br />

        {% if object_list %}
            {% for post in object_list %}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {{ post.modify_date|date:"Y-m-d" }}
                <p>{{ post.description }}</p>
            {% endfor %}

        {% elif search_term %}
        <b><i>Search Word({{ search_term }}) Not Found !</i></b>
        {% endif %}
    </div>
{% endblock %}