pdp_django/blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView().as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView().as_view(), name='delete'),
]

pdp_django/pdp_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from pdp_django.views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, insecure=True) + static(settings.ASSETS_URL, document_root=settings.ASSETS_ROOT, insecure=True)

handler400 = 'pdp_django.views.custom_400'
handler403 = 'pdp_django.views.custom_403'
handler404 = 'pdp_django.views.custom_404'
handler500 = 'pdp_django.views.custom_500'

pdp_django/photo/urls.py
from django.conf.urls import url
#from django.views.generic import ListView, Detailview
from photo.views import *
from photo.models import Album, Photo

app_name = 'photo'

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name='index'),
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
    url(r'^album/add/$', AlbumPhotoCV.as_view(), name='album_add'),
    url(r'^album/change/$', AlbumChangeLV.as_view(), name='album_change'),
    url(r'^album/(?P<pk>[0-9]+)/update/$', AlbumPhotoUV.as_view(), name='album_update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    url(r'^photo/add/$', PhotoCreateView.as_view(), name='photo_add'),
    url(r'^photo/change/$', PhotoChangeLV.as_view(), name='photo_change'),
    url(r'^photo/(?P<pk>[0-9]+)/update/$', PhotoUpdateView.as_view(), name='photo_update'),
    url(r'^photo/(?P<pk>[0-9]+)/delete/$', PhotoDeleteView.as_view(), name='photo_delete'),
]

pdp_django/photo/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.urls import reverse #django 버젼이 1.10 이상일 경우
from photo.fields import ThumbnailImageField

from django.contrib.auth.models import User

# Create your models here.
@python_2_unicode_compatible
class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User,  null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))

@python_2_unicode_compatible
class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE) #https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.ForeignKey.on_delete 참조
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

pdp_django/photo/forms.py
from photo.models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(
    Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2)

pdp_django/photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy #django 버젼이 1.10 이상일 경우
from pdp_django.views import LoginRequiredMixin
from django.shortcuts import redirect
from photo.forms import PhotoInlineFormSet

from django.shortcuts import render

# Create your views here.
class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    #model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['album', 'title', 'image', 'description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')

class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset'];
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    field = ['name', 'description']
    template_name = 'photo/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

pdp_django/photo/templates/photo/album_change_list.html
{% extends "base.html" %}

{% block title %}Album-Photo List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Album Change - {{user}}</h1>

        <table class="change-list">
            <tr>
                <th>이름</th>
                <th>설명</th>
                <th>소유자</th>
                <th>수정</th>
                <th>삭제</th>
            </tr>

            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description|linebreaks }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">수정</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">삭제</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

pdp_django/photo/templates/photo/album_confirm_delete.html
{% extends "base.html" %}

{% block title %}Album-Photo Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Photo-Album Delete - 사용자 : {{user}}</h1>

    <form action="" method="post">{% csrf_token %}
        <p>정말로 해당 앨범 [ "{{ object }}" ] 을(를) 삭제하시겠습니까 ?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>
{% endblock %}

pdp_django/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}Album Detail{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h2 style="display:inline">{{ object.name }}</h2>
        &emsp;<b><i>{{ object.description }}</i></b>

        <hr />

        <div class="album-detail">
            {% for photo in object.photo_set.all %}
                <div class="album-detail-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
                    </a>
                    <li>{{ photo.title }}</li>
                    <li>{{ photo.upload_date|date:"Y-m-d" }}</li>
                </div>
            {% endfor %}
        </div>
        <br />
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
{% endblock %}

pdp_django/photo/templates/photo/album_form.html
{% extends "base.html" %}

{% block title %}Album-Photo Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Album-Photo InlineFormSet</h1>
            {% if form.is_multipart or formset.is_multipart %}
            <form enctype="multipart/form-data" method="post" action=".">
            {% else %}
            <form method="post" action=".">
            {% endif %}
            {% csrf_token %}

                {% if form.errors or formset.errors %}
                <p class="errornote">앗 이런! 입력한 내용에 문제가 있네요.</p>
                {% endif %}

                <h4>앨범 내용 추가 및 수정</h4>

                <fieldset class="aligned">
                    <div class="form-row">{{ form.name.label_tag }} {{ form.name }}</div>
                    <div class="form-row">{{ form.description.label_tag }} {{ form.description }}</div>
                </fieldset>

                <h4>사진 내용 추가 및 수정</h4>
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form.id }}
                    <fieldset class="aligned">
                        <div class="form-row">{{ form.image.label_tag }} {{ form.image }}</div>
                        <div class="form-row">{{ form.title.label_tag }} {{ form.title }}</div>
                        <div class="form-row">{{ form.description.label_tag }} {{ form.description }}</div>
                    </fieldset>
                {% endfor %}

                <div class="submit-row">
                    <input type="submit" value="Submit" />
                </div>

                <script type="text/javascript">$('#id_name').focus();</script>
            </form>
    </div>
{% endblock %}

pdp_django/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}Album List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
    <div id="content">
        {% for item in object_list %}
            <div class="clear_float">
                <h2 style="display:inline;"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
                &emsp;<b><i>{{ item.description }}</i></b>
            </div>

            <hr>

            <div class="album-list">
                {% for photo in item.photo_set.all|slice:":5" %}
                <div class="album-list-photo">
                    <a href="{{ photo.get_absolute_url }}">
                        <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
                    </a>
                </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

pdp_django/photo/templates/photo/photo_change_list.html
{% extends "base.html" %}

{% block title %}Photo List{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Photo Change - {{user}}</h1>

        <table class="change-list">
            <tr>
                <th>앨범</th>
                <th>제목</th>
                <th>설명</th>
                <th>소유자</th>
                <th>수정</th>
                <th>삭제</th>
            </tr>

            {% for item in object_list %}
            <tr>
                <td>{{ item.album }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description|linebreaks }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:photo_update' item.id %}">수정</a></td>
                <td><a href="{% url 'photo:photo_delete' item.id %}">삭제</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

pdp_django/photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}Photo Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Photo Delete - 사용자 : {{user}}</h1>

    <form action="" method="post">{% csrf_token %}
        <p>정말로 해당 사진 [ "{{ object }}" ] 을(를) 삭제하시겠습니까 ?</p>
        <input type="submit" value="Confirm" />
    </form>
</div>
{% endblock %}

pdp_django/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}Photo Detail{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h2>{{ object.title }}</h2>

        <table class="photo-detail">
            <tr>
                <td>
                    <a href="{{ object.image.url }}">
                        <img style="max-width: 100%" src="{{ object.image.url }}" />
                    </a>
                </td>

                <td>
                    <ul>
                        <li>Photo description</li>
                        {% if object.description %}<p>{{ object.descroption|linebreaks }}</p>
                        {% else %}<p>-</p>{% endif %}
                        <li>Date Uploaded</li>
                        <p>{{ object.upload_date }}</p>
                        <li>Album Name</li>
                        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
                    </ul>
                </td>
            </tr>
        </table>
        <br />
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>
{% endblock %}

pdp_django/photo/templates/photo/photo_form.html
{% extends "base.html" %}

{% block title %}Photo Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Photo Create / Update - {{user}}</h1>
        {% if form.is_multipart or formset.is_multipart %}
        <form enctype="multipart/form-data" method="post" action=".">
            {% else %}
            <form method="post" action=".">
                {% endif %}
                {% csrf_token %}

                {% if form.errors or formset.errors %}
                <p class="errornote">앗 이런! 입력한 내용에 문제가 있네요.</p>
                {% endif %}

                <p>사진을 추가하거나 수정할 수 있습니다.</p>

                <fieldset class="aligned">
                    <div class="form-row">{{ form.image.label_tag }} {{ form.image }}</div>
                    <div class="form-row">
                        {{ form.album.label_tag }} {{ form.album }}
                        <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a></button>
                    </div>
                    <div class="form-row">{{ form.title.label_tag }} {{ form.title }}</div>
                    <div class="form-row">{{ form.description.label_tag }} {{ form.description }}</div>
                </fieldset>
                {% endfor %}

                <div class="submit-row">
                    <input type="submit" value="Submit" />
                </div>

                <script type="text/javascript">$('#id_album').focus();</script>
            </form>
    </div>
{% endblock %}