pdp_django/blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView().as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView().as_view(), name='delete'),
]

pdp_django/pdp_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from pdp_django.views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, insecure=True) + static(settings.ASSETS_URL, document_root=settings.ASSETS_ROOT, insecure=True)

handler400 = 'pdp_django.views.custom_400'
handler403 = 'pdp_django.views.custom_403'
handler404 = 'pdp_django.views.custom_404'
handler500 = 'pdp_django.views.custom_500'

pdp_django/photo/urls.py
from django.conf.urls import url
#from django.views.generic import ListView, Detailview
from photo.views import *
from photo.models import Album, Photo

app_name = 'photo'

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name='index'),
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),
    url(r'^album/add/$', AlbumPhotoCV.as_view(), name='album_add'),
    url(r'^album/change/$', AlbumChangeLV.as_view(), name='album_change'),
    url(r'^album/(?P<pk>[0-9]+)/update/$', AlbumPhotoUV.as_view(), name='album_update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),
    url(r'^photo/add/$', PhotoCreateView.as_view(), name='photo_add'),
    url(r'^photo/change/$', PhotoChangeLV.as_view(), name='photo_change'),
    url(r'^photo/(?P<pk>[0-9]+)/update/$', PhotoUpdateView.as_view(), name='photo_update'),
    url(r'^photo/(?P<pk>[0-9]+)/delete/$', PhotoDeleteView.as_view(), name='photo_delete'),
]

pdp_django/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

pdp_django/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block title %}Django Web Programming{% endblock %}</title>

        {% load staticfiles %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/main.css' %}" rel="stylesheet">
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

        <!--[if lt IE 9]>
        <script src="{% static 'js/html5shiv.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
        <![endif]-->

        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

        <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
    </head>
    <body>
        <header id="header">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 overflow">
                        <div class="social-icons pull-right">
                            <ul class="nav nav-pills">
                                <li><a target="_blank" href="https://www.facebook.com/minovs"><i class="fa fa-facebook"></i></a></li>
                                <li><a target="_blank" href="https://plus.google.com/118152748218641637043"><i class="fa fa-google-plus"></i></a></li>
                                <li><a target="_blank" href="https://www.linkedin.com/in/minov87/"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar navbar-inverse" role="banner">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="{% url 'home' %}">
                            <h1><img src="images/logo.png" alt="logo"></h1>
                        </a>

                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="{% url 'home' %}">Home</a></li>
                            <li class="dropdown"><a href="{% url 'bookmark:index' %}">Bookmark <i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{% url 'bookmark:add' %}">Add</a></li>
                                    <li><a href="{% url 'bookmark:change' %}">Change</a></li>
                                </ul>
                            </li>
                            <li class="dropdown"><a href="{% url 'blog:index' %}">Blog <i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{% url 'blog:add' %}">Add</a></li>
                                    <li><a href="{% url 'blog:change' %}">Change</a></li>
                                </ul>
                            </li>
                            <li class="dropdown"><a href="{% url 'photo:index' %}">Photo <i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{% url 'photo:album_add' %}">Album Add</a></li>
                                    <li><a href="{% url 'photo:photo_add' %}">Photo Add</a></li>
                                    <li><a href="{% url 'photo:album_change' %}">Album Change</a></li>
                                    <li><a href="{% url 'photo:photo_change' %}">Photo Change</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
                            <li><a href="{% url 'admin:index' %}">Admin</a></li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_active %}
                            <li><a href="#">Hello, {% firstof user.get_short_name user.get_username %}</a></li>
                            <li><a href="{% url 'password_change' %}">Change pwd</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'login' %}">Login</a></li>
                            <li><a href="{% url 'register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="search">
                        <form action="/blog/search/" method="post"> {% csrf_token %}
                            <i class="fa fa-search"></i>
                            <div class="field-toggle">
                                <input type="text" name="search_word" id="id_search_word" class="search-form" autocomplete="off" placeholder="Search">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </header>

        <section id="page-breadcrumb">
            <div class="vertical-center sun">
                <div class="container">
                    <div class="row">
                        <div class="action">
                            <div class="col-sm-12">
                                <h1 class="title">{% block top_title %}Main{% endblock %}</h1>
                                <p>{% block top_desc %}{% endblock %}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/#page-breadcrumb-->

        <section id="blog-details" class="padding-top">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </section>
        <!--/#blog-->

        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 text-center bottom-separator">
                        <img src="{% static 'images/home/under.png'%}" class="img-responsive inline" alt="">
                    </div>
                    <div class="col-md-3 col-sm-6" style="margin-left:35%">
                        <div class="contact-info bottom">
                            <h2>Contacts</h2>
                            <address>
                                E-mail: <a href="mailto:minov@minov.co.kr">minov@minov.co.kr</a> <br>
                            </address>

                            <h2>Address</h2>
                            <address>
                                Republic of Korea <br>
                            </address>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="copyright-text text-center">
                            <p>&copy; Minov 2017. All Rights Reserved.</p>
                            <p>Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--/#footer-->
    </body>
</html>

pdp_django/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock%}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
    <div id="content_home">
        <hr style="margin: 5px 0;">

        <h2>Select App</h2>

        <table id="applist">
            <tr>
                <td><a class="abi" href="{% url 'bookmark:index' %}">Bookmark</a></td>
                <td>Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~</td>
                <td class="Edit"><a class="ai" href="{% url 'bookmark:add' %}">Add</a></td>
                <td class="Edit"><a class="ai" href="{% url 'bookmark:change' %}">Change</a></td>
            </tr>

            <tr>
                <td><a class="abi" href="{% url 'blog:index' %}">Blog</a></td>
                <td>Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~</td>
                <td class="Edit"><a class="ai" href="{% url 'blog:add' %}">Add</a></td>
                <td class="Edit"><a class="ai" href="[% url 'blog:change' %]">Change</a></td>
            </tr>

            <tr>
                <td><a class="abi" href="{% url 'photo:index'%}">Photo</a></td>
                <td>Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~ Blah~</td>
                <td class="Edit"><a class="ai" href="{% url 'photo:album_add' %}">Add</a></td>
                <td class="Edit"><a class="ai" href="{% url 'photo:album_change' %}">Change</a></td>
            </tr>
        </table>
    </div>
{% endblock content %}

{% block footer %}
    <div id="footer">
        &copy; Minov 2017
    </div>
{% endblock footer %}