pdp_django/blog/urls.py
from django.conf.urls import url
from blog.views import *

app_name = 'blog'

urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<slug>[-\w]+)/$', PostDV.as_view(), name='post_detail'),
    url(r'^archive/$', PostAV.as_view(), name='post_archive'),
    url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$', PostMAV.as_view(), name='post_month_archive'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),
    url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
    url(r'^tag/$', TagTV.as_view(), name='tag_cloud'),
    url(r'^tag/(?P<tag>[^/]+(?u))/$', PostTOL.as_view(), name='tagged_object_list'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
    url(r'^add/$', PostCreateView.as_view(), name='add'),
    url(r'^change/$', PostChangeLV.as_view(), name='change'),
    url(r'^(?P<pk>[0-9]+)/update/$', PostUpdateView().as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', PostDeleteView().as_view(), name='delete'),
]

pdp_django/bookmark/urls.py
from django.conf.urls import url
#from bookmark.views import BookmarkLV, BookmarkDV
from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    url(r'^$', BookmarkLV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
    url(r'^add/$', BookmarkCreateView.as_view(), name='add'),
    url(r'^change/$', BookmarkChangeLV.as_view(), name='change'),
    url(r'^(?P<pk>[0-9]+)/update/$', BookmarkUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', BookmarkDeleteView.as_view(), name='delete'),
]

pdp_django/pdp_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from pdp_django.views import *

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^photo/', include('photo.urls', namespace='photo')),

    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, insecure=True) + static(settings.ASSETS_URL, document_root=settings.ASSETS_ROOT, insecure=True)

handler400 = 'pdp_django.views.custom_400'
handler403 = 'pdp_django.views.custom_403'
handler404 = 'pdp_django.views.custom_404'
handler500 = 'pdp_django.views.custom_500'

pdp_django/bookmark/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
@python_2_unicode_compatible
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

pdp_django/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from pdp_django.views import LoginRequiredMixin

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(BookmarkCreateView, self).form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

pdp_django/bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}Django Bookmark Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark 수정 - 사용자 : {{user}}</h1>

        <table class="change-list">
            <tr>
                <th>제목</th>
                <th>Url</th>
                <th>등록자</th>
                <th>수정</th>
                <th>삭제</th>
            </tr>

            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookmark:update' item.id %}">수정</a></td>
                    <td><a href="{% url 'bookmark:delete' item.id %}">삭제</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

pdp_django/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}Django Bookmark Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark Delete - 사용자 : {{user}}</h1>

        <form action="" method="post">{% csrf_token %}
            <p>정말로 해당 북마크 [ "{{ object }}" ] 를 삭제하시겠습니까 ?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
{% endblock %}

pdp_django/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
    <div id="content">
        <h1>{{object.title}}</h1>
        <ul>
            <li>URL : <a href="{{object.url}}">{{object.url}}</a></li>
        </ul>
    </div>
{% endblock %}

pdp_django/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}

{% block title %}Django Bookmark Form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark 추가/수정 - 사용자 : {{user}}</h1>

        <form action="." method="post">{% csrf_token %}
            {% if form.errors %}
                <p class="errornote">앗 이런! 입력한 내용에 문제가 있네요.<</p>
            {% endif %}

            <p>본인의 북마크를 추가하거나 수정할 수 있습니다.</p>

            <fieldset class="aligned">
                <div class="form-row">
                    {{ form.title.label_tag }} {{ form.title }}
                </div>
                <div class="form-row">
                    {{ form.url.label_tag }} {{ form.url }}
                </div>
            </fieldset>

            <div class="submit-row">
                <input type="submit" value="submit" />
            </div>

            <script type="text/javascript">$('#id_title').focus();</script>
        </form>
    </div>
{% endblock %}

pdp_django/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}Django Bookmark List{% endblock %}

{% block content %}
    <div id="content">
        <h1>Bookmark List</h1>
        <ul>
            {% for bookmark in object_list %}
                <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}